apiVersion: k3d.io/v1alpha4
kind: Simple

# enable caching for our node
volumes:
- volume: var-lib-rancher-k3s-server-0:/var/lib/rancher/k3s/agent/containerd
  nodeFilters:
  - server:0

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

hostAliases:
  - ip: 10.43.10.10
    hostnames:
      - gitea.localhost

