apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: opentelemetry-demo

manifests:
  kustomize:
    paths:
      - opentelemetry-demo/preview

deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kubeflow

requires:
  - configs: ["kubeflow-crds"]

manifests:
  kustomize:
    paths:
      - kubeflow/preview

deploy:
  statusCheck: false
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kubeflow-crds

manifests:
  rawYaml:
    - kubeflow/crds/*

deploy:
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: gitea

deploy:
  helm:
    releases:
      - name: gitea
        remoteChart: gitea
        repo: https://dl.gitea.io/charts/
        version: 8.3.0
        namespace: gitea
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - tasks/gitea.values.yaml

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: argocd

manifests:
  kustomize:
    paths:
      - argocd

deploy:
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: argocd-apps

requires:
  - configs: ["argocd"]

manifests:
  rawYaml:
    - argocd/app-of-apps.yaml
  kustomize:
    paths:
      # contains preconfigured secret to make login easier during the demo
      - gitlab

deploy:
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: linkerd

requires:
- configs:
    - linkerd-crds
    - linkerd-control-plane
    - linkerd-viz

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: linkerd-crds

deploy:
  helm:
    releases:
      - name: linkerd-crds
        remoteChart: linkerd-crds
        repo: https://helm.linkerd.io/stable
        namespace: linkerd-system
        wait: true
        createNamespace: true
        upgradeOnChange: true

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: linkerd-control-plane

requires:
- configs: ["linkerd-crds"]

deploy:
  helm:
    releases:
      - name: linkerd-control-plane
        remoteChart: linkerd-control-plane
        repo: https://helm.linkerd.io/stable
        namespace: linkerd
        createNamespace: true
        upgradeOnChange: true
        wait: true
        setFiles:
          identityTrustAnchorsPEM: tasks/certs/ca.crt
          identity.issuer.tls.crtPEM: tasks/certs/issuer.crt
          identity.issuer.tls.keyPEM: tasks/certs/issuer.key

--- 

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: linkerd-viz

requires:
- configs: ["linkerd"]

deploy:
  helm:
    releases:
      - name: linkerd-viz
        remoteChart: linkerd-viz
        repo: https://helm.linkerd.io/stable
        namespace: linkerd-viz
        createNamespace: true
        upgradeOnChange: true
        wait: true
