apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kuberay

deploy:
  helm:
    releases:
      - name: kuberay-operator
        remoteChart: kuberay-operator
        repo: https://ray-project.github.io/kuberay-helm/
        version: v0.5.0
        namespace: kuberay
        createNamespace: true
        upgradeOnChange: true

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kubeflow

requires:
  - configs: ["kubeflow-crds"]

manifests:
  kustomize:
    paths:
      - kubeflow/preview

deploy:
  statusCheck: false
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kubeflow-crds

manifests:
  rawYaml:
    - kubeflow/crds/*

deploy:
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: gitea

deploy:
  helm:
    releases:
      - name: gitea
        remoteChart: gitea
        repo: https://dl.gitea.io/charts/
        namespace: gitea
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - tasks/gitea.values.yaml

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: argocd

manifests:
  kustomize:
    paths:
      - argocd

deploy:
  kubectl: {}

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: argocd-apps

requires:
  - configs: ["argocd"]

manifests:
  rawYaml:
    - argocd/app-of-apps.yaml
  kustomize:
    paths:
      # contains preconfigured secret to make login easier during the demo
      - gitlab

deploy:
  kubectl: {}
