# https://taskfile.dev

version: '3'

set:
  - "errexit"
  - "nounset"
  - "pipefail"

includes:
  dev: .devcontainer
  demo: ./tasks/Taskfile.demo.yml
  kubeflow: ./tasks/Taskfile.kubeflow.yml
  vcluster: 
    taskfile: ./tasks/Taskfile.vcluster.yml
    internal: true
  tools: 
    taskfile: ./tasks/Taskfile.tools.yml
    internal: true

tasks:
  create-env:
    desc: "Create the vcluster"
    deps:
      - task: tools:ensure-kubectl
      - task: tools:ensure-helm
      - task: tools:ensure-kustomize
      - task: tools:ensure-skaffold
    env:
      SKAFFOLD_LABEL: skaffold.dev/run-id=identifier-to-make-skaffold-idempotent
    cmds:
      - task: vcluster:create
      - task: vcluster:connect
      - defer: { task: vcluster:disconnect }

      - task: kubeflow:set-domain
      - cmd: skaffold deploy -m kubeflow

      # - cmd: kubectl wait --for=condition=established crds/rayjobs.ray.io
      # - cmd: kubectl apply -n kuberay -f https://github.com/ray-project/kuberay/raw/master/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml

  list-env:
    desc: "List all vclusters"
    cmds:
      - task: vcluster:list

  delete-env:
    desc: "Destroy the vcluster"
    cmds:
      - task: vcluster:delete 

  build-pipeline:
    desc: "Build a pipeline from python code"
    deps:
      - task: tools:ensure-kfp1
    cmds:
      - ./pipeline.py

  deploy-pipeline:
    deps:
      - task: tools:ensure-kubectl
    preconditions:
      - sh: test -n "{{.VCLUSTER_NAME}}"
        msg: "missing VCLUSTER_NAME environment variable"
    cmds:
      - task: vcluster:connect
      - defer: { task: vcluster:disconnect }
      - kubectl port-forward -n kubeflow svc/ml-pipeline-ui 8080:80 &
      - task: kubeflow:wait-for-api
      - task: kubeflow:upload-pipeline
