apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-manifests.yaml

patches:
- target:
    kind: Service
    name: frontend-external
  patch: |-
    - op: remove
      path: /spec/type