apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

replacements:
- source:
    fieldPath: metadata.annotations.preview/domain
    kind: Ingress
    name: kubeflow-dashboard
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: kubeflow-dashboard
