apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/stefanprodan/podinfo//kustomize?ref=6.4.1

patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |
      - op: test
        path: "/spec/template/spec/containers/0/name"
        value: "podinfod"
      - op: remove
        path: "/spec/template/spec/containers/0/env"
      - op: add
        path: "/spec/template/spec/containers/0/envFrom"
        value:
          - configMapRef:
              name: podinfo-config
