# https://taskfile.dev

version: '3'

includes:
  tools: 
    taskfile: Taskfile.tools.yml
    internal: true

tasks:
  up:
    desc: "Setup the demo"
    cmds:
      - task: tools:ensure-gitea-remote
      - task: tools:ensure-gitlab-remote
      - task: create
      - task: deploy-gitea
      - task: deploy-argocd
      # wait for argocd to deploy gitlab then wait for gitlab to wake up and push the repo
      - until git push --tags gitlab main; do sleep 5; done

  down:
    desc: "Take down the cluster and everything in it"
    cmds:
      - k3d cluster delete

  create:
    internal: true
    desc: "Start the cluster"
    cmds:
      - k3d cluster create --config k3d-config.yaml
      - until kubectl wait --for condition=ready pods -l k8s-app=kube-dns -n kube-system; do sleep 2; done
    status:
      - k3d cluster list --no-headers | grep k3s-default > /dev/null

  deploy-gitea:
    internal: true
    desc: "Deploy Gitea"
    cmds:
      - skaffold deploy -m gitea
      # push the current repo into gitea
      - kubectl wait --for=condition=ready pod -n gitea gitea-0 --timeout 300s
      - until git push --tags gitea main; do sleep 5; done

  deploy-argocd:
    internal: true
    desc: "Deploy ArgocD and its apps"
    cmds:
      - skaffold deploy -m argocd-apps

  slides:
    desc: "Start the slides"
    dir: slides
    deps:
      - task: tools:ensure-slides
      - task: tools:ensure-figlet
    cmds:
      - ./bin/slides slides.md

