apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique

resources:
- namespace.yaml
- ingress.yaml
- ../base

replacements:
- source:
    fieldPath: metadata.annotations.preview/domain
    kind: Ingress
    name: boutique
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: boutique
commonAnnotations:
  preview/domain: b.localhost
