# https://taskfile.dev

version: '3'

tasks:
  # devcontainer specific commands. This mimics what vscode does with the dev container extension.
  # it requires the @devcontainers/cli node package to be installed. The ensure-devcontainer task
  # will attempt to install it if it's missing.
  up:
    desc: "Launch a devcontainer."
    deps:
      - task: ensure-devcontainer
    cmds:
      - |
        devcontainer up --workspace-folder . \
        {{if .SSH_AUTH_SOCK -}}
        --mount type=bind,source={{.SSH_AUTH_SOCK}},target={{.SSH_AUTH_SOCK}} \
        {{end -}}
        --id-label=dev.containers.id={{.ROOT_DIR}}

  rebuild:
    desc: "Rebuild a devcontainer."
    deps:
      - task: ensure-devcontainer
    cmds:
      - devcontainer build --workspace-folder .

  shell:
    desc: "Start a shell in the devcontainer."
    interactive: true
    deps:
      - task: up
    ignore_error: true
    cmds:
      - |
        devcontainer exec --workspace-folder . \
        --id-label=dev.containers.id={{.ROOT_DIR}} \
        {{if .SSH_AUTH_SOCK -}}
        --remote-env SSH_AUTH_SOCK={{.SSH_AUTH_SOCK}} \
        {{end -}}
        zsh

  stop:
    desc: "Stop the devcontainer."
    deps:
      - task: ensure-devcontainer
    vars:
      DEVCONTAINER_ID:
        sh: 'docker ps -a -q -f label="dev.containers.id={{.ROOT_DIR}}"'
    preconditions:
      - sh: '[[ -n "{{.DEVCONTAINER_ID}}" ]]'
        msg: 'devcontainer with label "dev.containers.id={{.ROOT_DIR}}" not found'
    cmds:
    - docker stop {{.DEVCONTAINER_ID}} > /dev/null

  down:
    desc: "Destroy the devcontainer."
    deps:
      - task: stop
    vars:
      DEVCONTAINER_ID:
        sh: 'docker ps -a -q -f label="dev.containers.id={{.ROOT_DIR}}"'
    preconditions:
      - sh: '[[ -n "{{.DEVCONTAINER_ID}}" ]]'
        msg: 'devcontainer with label "dev.containers.id={{.ROOT_DIR}}" not found'
    cmds:
      - docker rm {{.DEVCONTAINER_ID}} --volumes > /dev/null

  ensure-devcontainer:
    internal: true
    silent: true
    preconditions:
      - sh: command -v npm
        msg: "npm is not installed or in your path"
    status:
      - command -v devcontainer
    cmds:
      - npm install -g @devcontainers/cli

