apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo

resources:
- ../base
- namespace.yaml
- ingress.yaml

patches:
- patch: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: opentelemetry-demo-grafana-test
      namespace: otel-demo
    $patch: delete
- patch: |
    - op: remove
      path: /spec/template/spec/containers/0/resources
  target:
    kind: Deployment

replacements:
- source:
    fieldPath: metadata.annotations.preview/domain
    kind: Ingress
    name: otel-demo
  targets:
  - fieldPaths:
    - spec.rules.0.host
    options:
      create: true
    select:
      kind: Ingress
      name: otel-demo
