apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    previewDomain: edgecase.rio.wtf

  service.github: |
    appID: 383353
    installationID: 41276697
    privateKey: $github-private-key

  template.app-deployed: |
    message: |
      Application is now running.
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: success
        label: "app/{{.app.metadata.name}}"
        targetURL: 'http://{{index .app.metadata.labels "preview/env"}}.{{.context.previewDomain}}/'

  template.app-syncing: |
    message: |
      Application is syncing.
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.operation.sync.revision}}"
      status:
        state: pending
        label: "app/{{.app.metadata.name}}"

  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.operationState.syncResult.revision
      send: [app-deployed]

  trigger.on-syncing: |
    - description: Application is syncing. Triggered once per commit.
      when: app.status.operationState != nil and app.status.operationState.phase in ['Running']
      send: [app-syncing]
