apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

replicas:
# we don't need it. Auth is disabled.
- name: argocd-dex-server
  count: 0

resources:
- namespace.yaml
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- install.yaml
- ingress.yaml
- github.repository.yaml
- wildcard.tlsstore.yaml

patches:
  - path: argocd-notifications.configmap.yaml
  - path: remove-argocd-notifications-secret.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
      - server.disable.auth=true
  - name: argocd-cm
    behavior: merge
    literals:
      - timeout.reconciliation=10s
