apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
- cloudflared.yaml
- namespace.yaml
- wildcard.tlsstore.yaml

configMapGenerator:
- name: cloudflared
  files:
    - config.yaml
