apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-clusters
  namespace: argocd
spec:
  generators:
    - pullRequest:
        gitea:
          owner: root
          repo: demo
          api: http://gitea.localhost/
          insecure: true
        requeueAfterSeconds: 5
  template:
    metadata:
      name: 'pr-{{number}}-{{branch_slug}}'
      labels:
        preview/env: 'pr-{{number}}-{{branch_slug}}'
      annotations:
        git/sha: '{{head_sha}}'
        git/branch: '{{branch}}'
        scm/pull-request: '{{number}}'
        scm/branch_slug: '{{branch_slug}}'
    spec:
      source:
        repoURL: https://charts.loft.sh
        chart: vcluster
        targetRevision: v0.15.0
        helm:
          releaseName: pr-{{number}}-{{branch_slug}}
          values: |
            sync:
              ingresses:
                enabled: true
            storage:
              persistence: false
            syncer:
              extraArgs:
                - --out-kube-config-secret=pr-{{number}}-{{branch_slug}}

      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: gitlab
      syncPolicy:
        automated:
          prune: true

---
 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow-crds-preview
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'kubeflow-crds-preview-{{nameNormalized}}'
      labels:
        preview/env: '{{metadata.labels.preview/env}}'
    spec:
      source:
        repoURL: http://gitea.localhost/root/demo.git
        path: kubeflow/crds
        targetRevision: '{{metadata.annotations.git/sha}}'
      project: default
      destination:
        server: '{{server}}'
        namespace: kubeflow
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: -1
          backoff:
            duration: 5s
            maxDuration: 10s

---
 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow-preview
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'kubeflow-preview-{{nameNormalized}}'
      labels:
        preview/env: '{{metadata.labels.preview/env}}'
    spec:
      source:
        repoURL: http://gitea.localhost/root/demo.git
        path: kubeflow/preview
        targetRevision: '{{metadata.annotations.git/sha}}'
        kustomize:
          commonAnnotations:
            preview/domain: '{{nameNormalized}}.localhost'
      project: default
      destination:
        server: '{{server}}'
        namespace: kubeflow
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: -1
          backoff:
            duration: 5s
            maxDuration: 10s
