apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-argocd-cluster-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  rules:
    - name: select-vcluster-credentials
      match:
        all:
          - resources:
              kinds:
                - Secret
              namespaces:
                - vclusters
              names:
                - pr-*
      context:
        - name: ownerUID
          apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: "metadata.uid"
        - apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: 'metadata.annotations."git/sha"'
          name: gitSHA
        - apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: 'metadata.annotations."git/branch"'
          name: gitBranch
        - apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: 'metadata.annotations."scm/pull-request"'
          name: scmPullRequest
        - apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: 'metadata.annotations."scm/branch-slug"'
          name: scmBranchSlug
        - apiCall:
            urlPath: "/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{request.object.metadata.name}}"
            jmesPath: 'metadata.labels."preview/domain"'
          name: previewDomain
        - name: config
          variable:
            jmesPath: "to_string(@)"
            value: |
              {
                "tlsClientConfig": {
                  "caData": "{{request.object.data."certificate-authority"}}",
                  "certData": "{{request.object.data."client-certificate"}}",
                  "keyData": "{{request.object.data."client-key"}}"
                }
              }

      generate:
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: "{{request.object.metadata.name}}"
        namespace: argocd
        data:
          kind: Secret
          metadata:
            labels:
              argocd.argoproj.io/secret-type: cluster
              preview/env: "{{request.object.metadata.name}}"
              preview/domain: "{{previewDomain}}"
            annotations:
              git/sha: "{{gitSHA}}"
              git/branch: "{{gitBranch}}"
              scm/pull-request: "{{scmPullRequest}}"
              scm/branch-slug: "{{scmBranchSlug}}"
            ownerReferences:
              - apiVersion: argoproj.io/v1alpha1
                blockOwnerDeletion: true
                kind: Application
                name: "{{request.object.metadata.name}}"
                uid: "{{ownerUID}}"
          stringData:
            name: "{{request.object.metadata.name}}"
            server: 'https://{{request.object.metadata.name}}.{{request.object.metadata.namespace}}'
            config: "{{config}}"
