apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-crds-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubeflow/crds
    repoURL: http://gitea.localhost/root/demo.git
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-production
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  project: default
  source:
    path: kubeflow/production
    repoURL: http://gitea.localhost/root/demo.git
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
