apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-preview
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'podinfo-preview-{{nameNormalized}}'
      labels:
        preview/env: '{{metadata.labels.preview/env}}'
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.github: "app-deployed"
    spec:
      source:
        repoURL: https://github.com/rio/enabling-experimentation-workshop.git
        path: podinfo/preview
        targetRevision: '{{metadata.annotations.git/branch}}'
        kustomize:
          commonAnnotations:
            preview/domain: '{{nameNormalized}}.localhost'
      project: default
      destination:
        server: '{{server}}'
        namespace: podinfo
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: -1
          backoff:
            duration: 5s
            maxDuration: 10s
