apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-dashboard
  namespace: kubeflow
spec:
  ingressClassName: traefik
  rules:
  - host: kubeflow.localhost
    http:
      paths:
      - backend:
          service:
            name: ml-pipeline-ui
            port:
              number: 80
        path: /
        pathType: Prefix
